name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload plugin files
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-plugin-build
          path: |
            main.js
            manifest.json
            styles.css
