name: Build and Release Obsidian Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        # Using Node.js 22.x as specified in the plugin's package.json
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload plugin files
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-plugin-build
          path: |
            main.js
            manifest.json
            styles.css

  upload_release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: obsidian-plugin-build
          path: ./release
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
