name: Release

on:
  workflow_run:
    workflows: ["Build CI"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: obsidian-plugin-build
          path: ./release

      # Example: upload to GitHub Release if desired
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
